### ISSUE TITLE
begin with bplusTree-file

### ISSUE THREAD

**Issue by turingF** [davidmoten/bplustree#1]
Some simple code begin:

'''
public class Mytest {
    public static void main(String[] args) {

        BPlusTree<Integer, Integer> tree = BPlusTree.file() //
                .directory(Testing.newDirectory()) // I copy your Testing class
                .clearDirectory() //
                .maxKeys(3) //
                .segmentSizeMB(1) //
                .keySerializer(Serializer.INTEGER) //
                .valueSerializer(Serializer.INTEGER) //
                .naturalOrder();

    }
    }
'''

And unfortunately error:

```
Exception in thread "main" java.lang.NoSuchMethodError: com.github.davidmoten.guavamini.Preconditions.checkNotNull(Ljava/lang/Object;)Ljava/lang/Object;
	at com.github.davidmoten.bplustree.BPlusTree$BuilderFile.directory(BPlusTree.java:67)
	at test.Mytest.main(Mytest.java:27)
```

sry I dont konw how to solve it:(

**Comment by davidmoten** [comment]
Looks like you are missing the guava-mini dependency. You can see it in the pom of bplustree.
