### ISSUE TITLE
class ([B and java.lang.Comparable are in module java.base of loader 'bootstrap')

### ISSUE THREAD

**Issue by arjunsk** [davidmoten/bplustree#39]
Hey Dave,

Thank you for sharing this library.

I am getting the below exception while inserting byte[] into Btree.

```
Exception in thread "main" java.lang.ClassCastException: class [B cannot be cast to class java.lang.Comparable ([B and java.lang.Comparable are in module java.base of loader 'bootstrap')
	at java.base/java.util.Comparators$NaturalOrderComparator.compare(Comparators.java:47)
	at com.github.davidmoten.bplustree.internal.Util.getLocation(Util.java:54)
	at com.github.davidmoten.bplustree.internal.Leaf.getLocation(Leaf.java:88)
	at com.github.davidmoten.bplustree.internal.Leaf.insert(Leaf.java:44)
	at com.github.davidmoten.bplustree.BPlusTree.insert(BPlusTree.java:262)
```

**Any thoughts on what could be the cause?**

I am implementing `Comparable` on Key, and `Serializable` on both Key and Value.  

Below are my code references:

Driver.java
``` java
        tree = BPlusTree.file().directory("")
                .maxLeafKeys(32)
                .maxNonLeafKeys(8)
                .segmentSizeMB(1)
                .keySerializer(Serializer.bytes(100))
                .valueSerializer(Serializer.bytes(100))
                .naturalOrder();
```

ByteConversion.java
```java
    public static byte[] convertToBytes(Object object)  {
        try (ByteArrayOutputStream bos = new ByteArrayOutputStream(); ObjectOutputStream out = new ObjectOutputStream(bos)) {
            out.writeObject(object);
            return bos.toByteArray();
        }catch (Exception ex){
            ex.printStackTrace();
        }
        return null;
    }

    public static Object convertFromBytes(byte[] bytes)  {
        try (ByteArrayInputStream bis = new ByteArrayInputStream(bytes); ObjectInputStream in = new ObjectInputStream(bis)) {
            return in.readObject();
        }catch (Exception ex){
            ex.printStackTrace();
        }
        return null;
    }
```

**Comment by davidmoten** [comment]
There is no natural order on byte[]. You have to set a comparator in the builder.

**Comment by arjunsk** [comment]
Thank you so much for your input!
